### ISSUE TITLE
A single, unexpected print layer is blocking airflow at the Facepiece grill

### ISSUE THREAD

**Issue by gregkrsak** [theunitymask/PRO-preview#2]
According to @hollywoodx (Keith) the Facepiece is printing with an extra layer on the inside of its grill.

He also says this is not related to infill or support settings.

This is preventing the PRO design from being functional.

**Comment by mkraske** [comment]
Please replace this component with the component from the HOME mask (and rename appropriately). They are the same physical part with different names.

-Matt
